## Estadística  Ejercicios

In [46]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import scipy
from scipy import stats

import random
import pickle as pkl

In [47]:
pip install pandas

In [48]:
# Versiones

print(f"numpy=={np.__version__}")
print(f"matplotlib=={matplotlib.__version__}")
print(f"scipy=={scipy.__version__}")

numpy==2.2.0
matplotlib==3.10.0
scipy==1.14.1


In [49]:
with open("FUELCONSUMPTION_CITY.pkl", "br") as f:
    fuel_city = pkl.load(f)
    
with open("FUELCONSUMPTION_HWY.pkl", "br") as f:
    fuel_hwy = pkl.load(f)

In [50]:
city_consumption # Gasto de combustible en la ciudad

array([ 9.9, 11.2,  6. , ..., 13.4, 12.9, 14.9], shape=(1067,))

In [51]:
fuel_hwy # Gasto de combustible en la autovía

array([ 6.7,  7.7,  5.8, ...,  9.8,  9.3, 10.2], shape=(1067,))

### Ejercicio 01:
- Define una función que tome como entrada un array y retorne la varianza. Apóyate en la siguiente fórmula:
$$ \mathbf{S^2} = \frac{1}{n} \sum_{i=1}^{n} (x_{i}^{2}- \overline{x}^2)$$

- Comprueba que funciona correctamente comparándola con _**np.var()**_.

In [52]:
def entrada_array(lista):
    lista = []
    
    np.var(lista)

In [53]:
print(entrada_array)

<function entrada_array at 0x00000217EB53C9A0>


### Ejercicio 02:
- Define una función que tome como entrada un array y retorne la desviación estándar. Apóyate en la siguiente fórmula:

$$ \mathbf{S} = \sigma = \sqrt{\frac{1}{n} \sum_{i=1}^{n} x_{i}^{2}- \overline{x}^2}$$

- Comprueba que funciona correctamente comprobándola con _**np.std()**_.

### Ejercicio 03:
- Define una función que tome como parámetro un array y retorne los siguientes estadísticos en forma de diccionario:
    - Mínimo
    - Máximo
    - Media
    - Cuartiles Q1, Q2 (mediana) y Q3
    - Rango intercuartil
    - Desviación estándar
- Prueba la función con los arrays **fuel_city** y **fuel_hwy**.

In [54]:

def fuel_city_hwy(fuel):
    #crear diccionario
    diccionario = dict()
    
# ESTADISTICA

    min = np.min(fuel)
    max = np.max(fuel)
    media = np.mean(fuel)
    Q1 = np.quantile(fuel, 0.25)
    Q2 = np.median(fuel)
    Q3 = np.quantile(fuel, 0.75)
    IQR = Q3 - Q1
    desvi = np.std(fuel)
    
# AGREGAR ESTADISTICA AL DICCIONARIO

    diccionario["min"] = min
    diccionario["max"] = max
    diccionario["mean"] = media
    diccionario["Q1"] = Q1
    diccionario["median"] = Q2
    diccionario["Q3"] = Q3
    diccionario["IQR"] = IQR
    diccionario["std"] = desvi
    
# HACER UN RETURN PARA RETORNAR EL DICCIONARIO

    return diccionario

# Función para pintar un gráfico

def pinta_grafico(fuel):
    min = np.min(fuel)
    max = np.max(fuel)
    media = np.mean(fuel)
    Q1 = np.quantile(fuel, 0.25)
    Q2 = np.median(fuel)
    Q3 = np.quantile(fuel, 0.75)
    IQR = Q3 - Q1
    desvi = np.std(fuel)
    
    plt.figure(figsize=(10, 6))
    plt.boxplot(fuel, showmeans=True, orientation="horizontal")
    plt.axvline(Q1, color="red", linestyle="dashed", linewidth=2, label=(f"Q1: {Q1:.1f}"))
    plt.axvline(Q3, color="green", linestyle="dashed", linewidth=2, label=(f"Q3: {Q3:.1f}"))
    plt.axvline(min, color="orange", linestyle="dashed", linewidth=2, label=(f"Min: {min:.1f}"))
    plt.axvline(max, color="black", linestyle="dashed", linewidth=2, label=(f"Max: {max:.1f}"))
    plt.axvline(media, color="red", linestyle="dashed", linewidth=2, label=(f"Media: {media:.1f}"))    
    plt.axvline(Q2, color="blue", linestyle="dashed", linewidth=2, label=(f"Q2: {Q2:.1f}"))
    plt.axvline(IQR, color="yellow", linestyle="dashed", linewidth=2, label=(f"IQR: {IQR:.1f}")) 
    plt.axvline(desvi, color="purple", linestyle="dashed", linewidth=2, label=(f"desvi: {desvi:.1f}"))
    
    print(fuel_city_hwy)        
    
"""print(f"Mediana combustible en ciudad: {np.median(fuel_city)}")
print(f"Mediana combustible en carretera: {np.median(fuel_hwy)}")

print(f"Mediana combustible en ciudad: {np.min(fuel_city)}")
print(f"Mediana combustible en carretera: {np.min(fuel_hwy)}")
print(f"Mediana combustible en ciudad: {np.max(fuel_city)}")
print(f"Mediana combustible en carretera: {np.max(fuel_hwy)}")"""
    
    
"""Q1 = np.quantile(a =fuel_city_hwy, q = 0.25, interpolation = "lower")
Q3 = np.quantile(a =fuel_city_hwy, q =  0.75, interpolation = "lower")

IQR = Q3 -Q1
print(IQR)
print(np.median(fuel_city_hwy))"""

  





   
     

'Q1 = np.quantile(a =fuel_city_hwy, q = 0.25, interpolation = "lower")\nQ3 = np.quantile(a =fuel_city_hwy, q =  0.75, interpolation = "lower")\n\nIQR = Q3 -Q1\nprint(IQR)\nprint(np.median(fuel_city_hwy))'

### Ejercicio 04:
- Define una función que toma un array como entrada, y retorna el mismo array sin los outliers.
- Utiliza la **Puntuación Z** para el filtrado de valores atípicos.
- Prueba la función con los arrays _**fuel_city**_ y _**fuel_hwy**_, y calcula qué porcentaje de datos se ha conservado tras el filtrado de outliers para cada caso.

### Ejercicio 05:
- Repite el ejercicio 4 usando la **Valla de Tukey** para el filtrado de outliers.

### Ejercicio 06:
- Define una función que tome como parámetro un array y dibuje un plot. El plot debe tener:
    - La distribución de los datos del array como un histograma de color verde pastel.
    - Una línea vertical de color rojo que represente el promedio.
    - Una línea vertical de color dorado que represente la mediana.
    - Dos líneas verticales discontinuas de color gris claro que representen $-z$ y $z$.
    - Dos líneas verticales discontinuas de color gris oscuro que representen $-3z$ y $3z$.
    - Los outliers se tienen que marcar con un color naranja chillón.
    
- Aprovecha las funciones del ejercicio 1 y del ejercicio 3 para obtener los estadísticos necesarios y filtrar los outliers.
- Guiate por los notebooks de teoría para cambiar el color de las gráficas y hacer las lineas verticales.

### Ejercicio 07:
- Define una función que estandarice los datos de un array usando la siguiente fórmula:

$$
z = \frac{x_{i} - \overline{x}}{\sigma_{x}} = \frac{x_{i} - mean(x)}{std(x)}
$$

- Prueba estandarizar un array y hacer un plot usando la función del ejercicio anterior. ¿Qué diferencias ves?

### Ejercicio 08:
- Aplica una transformación de logaritmo neperiano (_**np.log**_) a los datos de **fuel_city** y **fuel_hwy** y vuelve a probar a usar la función del ejercicio 6.
- ¿Cómo son ahora las distribuciones?
- ¿Qué ocurre con los outliers?

### Ejercicio 09:
- Defina una función que calcule la correlación entre dos arrays. Apoyate en las siguientes fórmulas:

$$
\Large Cov(X, Y) = \frac{\sum_{i=1}^{n}(x_{i} - \bar{x})(y_{i} - \bar{y})}{n}\\
$$

<br>

$$
\Large \rho = \frac{Cov(X, Y)}{\sigma_{x}\sigma_{y}}
$$

- Usa la función para calcular la correlación entre **fuel_city** y **fuel_hwy**.
- Comprueba que funciona correctamente contrastando con el resultado de la función _**stats.pearsonr()**_.

### Ejercicio 10:
- Elige un array y toma 50 elementos aleatorios. Calcula las estadísticas para ese nuevo conjunto de datos.
- ¿Son similares estos resultados a los obtenidos de la población total?

### Ejercicio 11:
- Repite el ejercicio anterior, esta vez creando 5 conjuntos de 50 elementos aleatorios.
    - Calcula las estadísticas para cada conjunto de 50 elementos, guarda estos datos.
    - Calcula las estadísticas de los resultados anteriores.
    - ¿Son similares estos datos con los obtenidos de la población total?
    - Prueba hacerlo creando 100 conjuntos de 50 elementos esta vez.

### Ejercicio 12:
- Realiza un contraste de hipótesis y comprueba si se gasta más combustible en la ciudad que en la autovía.
    - **fuel_city**: gasto en ciudad
    - **fuel_hwy**: gasto en autovía
    - $H_0$: el gasto de combustible en la ciudad es igual o menor al gasto en la autovía.
    - $H_1$: el gasto de combustible en la ciudad es mayor al gasto en la autovía.
    
_**Pista**: hay que aplicar una prueba **t de Student** para **muestras pareadas** `stats.ttest_rel()`, o una prueba **Wilcoxon** para **muestras pareadas** `stats.wilcoxon()`, dependiendo de si se cumplen los supuestos de normalidad y homogeneidad de varianzas. Pueden especificar el parámetro `alternative` con el argumento `"greater"` para un contraste de tipo `a>b`._

In [66]:
with open("FUELCONSUMPTION_CITY.pkl", "br") as f:
    city_consumption = pkl.load(f)
    
city_consumption


FileNotFoundError: [Errno 2] No such file or directory: 'FUELCONSUMPTION_CITY.pkl'

In [56]:
with open("FUELCONSUMPTION_CITY.pkl", "br") as f:

    road_consumption = pkl.load(f)
road_consumption

array([ 9.9, 11.2,  6. , ..., 13.4, 12.9, 14.9], shape=(1067,))

In [57]:


print(city_consumption[:5])
print(road_consumption[:5])

[ 9.9 11.2  6.  12.7 12.1]
[ 9.9 11.2  6.  12.7 12.1]


In [58]:
# nivel de significancia para aceptae o rechazar pruebas

alpha = 0.05

In [59]:
# normalidad: combina skew y curtosis
_, p_city = stats.normaltest(city_consumption)
_, p_road = stats.normaltest(road_consumption)

print("pruebas de normalidad")
print(f"p_city{p_city} y p_road {p_road}")

pruebas de normalidad
p_city6.448140852748941e-29 y p_road 6.448140852748941e-29


In [60]:
# homogeneidad de varianza: es decir que la varianzas
# de de city_comsumption sea similar a la avrianza de road_consumption

_, p_var = stats.levene(city_consumption, road_consumption)

print("pruebas de varianza")
print(f"p_var {p_var}")


pruebas de varianza
p_var 1.0


In [61]:
# comprobar valores p versus significancia (a):

if p_city > alpha and p_road > alpha and p_var > alpha:
    print("Se cumple la asunción de NORMALIDAD Y HOMOGENEIDAD DE VARIANZAS")
else:
    print(" No se cumplen la asunción de NORMALIDAD Y HOMOGENEIDAD DE VARIANZAS")

        

 No se cumplen la asunción de NORMALIDAD Y HOMOGENEIDAD DE VARIANZAS


In [62]:
suposiciones =  p_city > alpha and p_road > alpha and p_var > alpha

if suposiciones:
    print("Se cumple la asunción de NORMALIDAD Y HOMOGENEIDAD DE VARIANZAS")
else:
    print(" No se cumplen la asunción de NORMALIDAD Y HOMOGENEIDAD DE VARIANZAS")


 No se cumplen la asunción de NORMALIDAD Y HOMOGENEIDAD DE VARIANZAS


In [63]:
print(f"mean_city_consumption {np.mean(city_consumption)}")
print(f"mean_road_consumption {np.mean(road_consumption)}")

mean_city_consumption 13.296532333645736
mean_road_consumption 13.296532333645736


In [64]:
# Contraste de hipótesis
if suposiciones:
    #prueba paramétrica
    _, p = stats.ttest_rel(city_consumption, road_consumption, alternativa= "greater")
else:
     _, p = stats.wilcoxon(city_consumption, road_consumption, alternativa= "greater")
     
print(f"contraste de hipótesis p-value: {p}")     
    
    

TypeError: wilcoxon() got an unexpected keyword argument 'alternativa'. Did you mean 'alternative'?

In [ ]:
if p < alpha:
    print("H1 VERDADERO (H alternativa)")
    print("H1 VERDADERO (H alternativa)")

In [ ]:
##############################################################################################################################